FROM node:18-alpine 

WORKDIR /workplace
COPY . .

RUN yarn
RUN yarn prisma generate
RUN yarn build

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "start"]
